### ISSUE TITLE
Migration to 2.x - timeout after 5000 seconds

### ISSUE THREAD

**Issue by denialanderror** [serenity-js/serenity-js#724]
I am attempting to migrate a fairly large Cucumber Protractor test suite from SerenityJS 1.x to 2.x and am having a number of difficulties. The main one currently is I get the following error, regardless of whether steps are passing or not:

```
✗ Execution failed with error (5s 880ms)

  Error: function timed out after 5000 milliseconds
      at errorFrom (/app/node_modules/@serenity-js/cucumber/src/listeners/cucumber-0.ts:172:33)
      at scenarioOutcomeFrom (/app/node_modules/@serenity-js/cucumber/src/listeners/cucumber-0.ts:141:26)
      at /app/node_modules/@serenity-js/cucumber/src/listeners/cucumber-0.ts:89:94
      at processTicksAndRejections (internal/process/task_queues.js:79:11)

```
For example, this simple function will through the above error:

``` 
actorCalled(user).attemptsTo(
          UseAngular.disableSynchronisation(),
          Wait.for(Duration.ofSeconds(30)),
          UseAngular.enableSynchronisation()
    )

```

I expect there is some missing configuration somewhere but I've been comparing with the examples and I can't see anything missing. Any suggestions would be appreciated.

I'd also note that I cannot get the examples to run. Attempting to run the protractor-cucumber example suite throws the following error - `E/launcher - Error: TypeError: Cannot set property 'defaultTimeout' of undefined` - and a similar issue occurs with the template - `Error message: Could not find update-config.json. Run 'webdriver-manager update' to download binaries` running with `npm test` after running `npm ci`.

**Comment by jan-molak** [comment]
Hey @denialanderror! 

> I expect there is some missing configuration somewhere but I've been comparing with the examples and I can't see anything missing. Any suggestions would be appreciated.

So the 5-second timeout feels like a [Cucumber step timeout](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/timeouts.md), which you might want to adjust either via `setDefaultTimeout` or per step.

> Attempting to run the protractor-cucumber example suite throws the following error
Which example are you referring to, please?

**Comment by denialanderror** [comment]
Thanks for the super quick response @jan-molak ! Looks like that was the issue.

The example I was referring to was [this one](https://github.com/serenity-js/serenity-js/tree/master/examples/protractor-cucumber).

I'd also note that it looks like v2.20.0 is no longer compatible with Cucumber 1.x as it no longer allows for the `compiler` option. If you'd like me to open a separate issue for that, please let me know.

**Comment by jan-molak** [comment]
Thanks @denialanderror, I'm glad it helped :-)

> The example I was referring to was this one.

This example uses [`chromedriver`](https://www.npmjs.com/package/chromedriver), so it shouldn't be trying to use `webdriver-manager update`. Could you please provide the exact steps for me to try and reproduce the issue you're seeing?

> I'd also note that it looks like v2.20.0 is no longer compatible with Cucumber 1.x as it no longer allows for the compiler option. If you'd like me to open a separate issue for that, please let me know.

Could you create a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) based on https://github.com/serenity-js/serenity-js-cucumber-protractor-template so that I can try to reproduce? Please downgrade the version of Cucumber to the exact one you're using and try to reflect your setup as closely as possible.

Thanks!
Jan

**Comment by denialanderror** [comment]
So I wasn't very clear in my first message about the errors in the template. It's actually two separate issues:

In the [cucumber-protractor _template_](https://github.com/serenity-js/serenity-js-cucumber-protractor-template), I get the following error:

```
[test:execute] [09:58:05] E/direct - Error code: 135
[test:execute] [09:58:05] E/direct - Error message: Could not find update-config.json. Run 'webdriver-manager update' to download binaries.
```

This is on a clean clone, then running `npm ci` followed by `npm test`.

The second issue I encountered was with the [cucumber-protractor _example_](https://github.com/serenity-js/serenity-js/tree/master/examples/protractor-cucumber), where I get this error:

```
E/launcher - Error: TypeError: Cannot set property 'defaultTimeout' of undefined
```

I get to this by running `npm install` followed by `npm test`

If I can get the template working, I'll get a minimal build on a separate ticket for the Cucumber version issue.

**Comment by saranyaeaswaran** [comment]
@denialanderror I'm also encountering the issue of 'Error: TypeError: Cannot set property 'defaultTimeout' of undefined' when I try use Cucumber with WebdriverIO, were you able to find a solution for this issue?

**Comment by viper3400** [comment]
Hi, it's been a while without any updates here. Let's try to summarize this issue:

@denialanderror got problems with 
* (1) [the Serenity/JS cucumber protractor template](https://github.com/serenity-js/serenity-js-cucumber-protractor-template)
* (2) [the protractor cucumber example from Serenity/JS repo](https://github.com/serenity-js/serenity-js/tree/master/examples/protractor-cucumber)

@saranyaeaswaran got problems with WebdriverIO and cucumber, but this would apply to
* (3) [the Serenity/JS cucumber webdriverio template](https://github.com/serenity-js/serenity-js-cucumber-webdriverio-template)

I was able to test (1) and (3) without any issues today (master branch, Serenity/JS version 2.33.2)

----

@saranyaeaswaran , if you still have issues on your side with cucumber webdriverio, would you mind to create a separate issue for it with some details of your implementation?

----

@jan-molak: But there is still a problem with (2). Not the one described in this issue, but the example `npm test` fails with 
```
Error: Cannot find module 'selenium-webdriver'
```
and `npm install` fails with
```
@serenity-js/protractor@2.33.2 requires a peer of selenium-webdriver@^3.6.0 but none is installed.
```

Seems, there was a [peer dependency to selenium-webdriver](https://github.com/serenity-js/serenity-js/blob/20c20c4d1322376f50510e14a97114b96747f9ac/packages/protractor/package.json#L66) introduced by PR #923. 

You've even [discussed](https://github.com/serenity-js/serenity-js/pull/923#discussion_r675988265) this in the PR review with @nchursin and that it should be a dev dependency instead of a peer, but somehow it made it to master branch.

**Comment by jan-molak** [comment]
> Seems, there was a [peer dependency to selenium-webdriver](https://github.com/serenity-js/serenity-js/blob/20c20c4d1322376f50510e14a97114b96747f9ac/packages/protractor/package.json#L66) introduced by PR https://github.com/serenity-js/serenity-js/pull/923.

Well spotted, let's fix that. Thanks!
